export const HttpStatus: Record<string | number, string> = Object.freeze({
	100: "Continue",
	101: "Switching Protocols",
	102: "Processing",
	200: "OK",
	201: "Created",
	202: "Accepted",
	203: "Non-authoritative Information",
	204: "No Content",
	205: "Reset Content",
	206: "Partial Content",
	207: "Multi-Status",
	208: "Already Reported",
	226: "IM Used",
	300: "Multiple Choices",
	301: "Moved Permanently",
	302: "Found",
	303: "See Other",
	304: "Not Modified",
	305: "Use Proxy",
	307: "Temporary Redirect",
	308: "Permanent Redirect",
	400: "Bad Request",
	401: "Unauthorized",
	402: "Payment Required",
	403: "Forbidden",
	404: "Not Found",
	405: "Method Not Allowed",
	406: "Not Acceptable",
	407: "Proxy Authentication Required",
	408: "Request Timeout",
	409: "Conflict",
	410: "Gone",
	411: "Length Required",
	412: "Precondition Failed",
	413: "Payload Too Large",
	414: "Request-URI Too Long",
	415: "Unsupported Media Type",
	416: "Requested Range Not Satisfiable",
	417: "Expectation Failed",
	418: "I'm a teapot",
	421: "Misdirected Request",
	422: "Unprocessable Entity",
	423: "Locked",
	424: "Failed Dependency",
	426: "Upgrade Required",
	428: "Precondition Required",
	429: "Too Many Requests",
	431: "Request Header Fields Too Large",
	444: "Connection Closed Without Response",
	451: "Unavailable For Legal Reasons",
	499: "Client Closed Request",
	500: "Internal Server Error",
	501: "Not Implemented",
	502: "Bad Gateway",
	503: "Service Unavailable",
	504: "Gateway Timeout",
	505: "HTTP Version Not Supported",
	506: "Variant Also Negotiates",
	507: "Insufficient Storage",
	508: "Loop Detected",
	510: "Not Extended",
	511: "Network Authentication Required",
	599: "Network Connect Timeout Error",
	ACCEPTED: "Accepted",
	ALREADY_REPORTED: "Already Reported",
	BAD_GATEWAY: "Bad Gateway",
	BAD_REQUEST: "Bad Request",
	CLIENT_CLOSED_REQUEST: "Client Closed Request",
	CONFLICT: "Conflict",
	CONNECTION_CLOSED_WITHOUT_RESPONSE: "Connection Closed Without Response",
	CONTINUE: "Continue",
	CREATED: "Created",
	EXPECTATION_FAILED: "Expectation Failed",
	FAILED_DEPENDENCY: "Failed Dependency",
	FORBIDDEN: "Forbidden",
	FOUND: "Found",
	GATEWAY_TIMEOUT: "Gateway Timeout",
	GONE: "Gone",
	HTTP_VERSION_NOT_SUPPORTED: "HTTP Version Not Supported",
	IM_A_TEAPOT: "I'm a teapot",
	IM_USED: "IM Used",
	INSUFFICIENT_STORAGE: "Insufficient Storage",
	INTERNAL_SERVER_ERROR: "Internal Server Error",
	LENGTH_REQUIRED: "Length Required",
	LOCKED: "Locked",
	LOOP_DETECTED: "Loop Detected",
	METHOD_NOT_ALLOWED: "Method Not Allowed",
	MISDIRECTED_REQUEST: "Misdirected Request",
	MOVED_PERMANENTLY: "Moved Permanently",
	MULTIPLE_CHOICES: "Multiple Choices",
	MULTI_STATUS: "Multi-Status",
	NETWORK_AUTHENTICATION_REQUIRED: "Network Authentication Required",
	NETWORK_CONNECT_TIMEOUT_ERROR: "Network Connect Timeout Error",
	NON_AUTHORITATIVE_INFORMATION: "Non-authoritative Information",
	NOT_ACCEPTABLE: "Not Acceptable",
	NOT_EXTENDED: "Not Extended",
	NOT_FOUND: "Not Found",
	NOT_IMPLEMENTED: "Not Implemented",
	NOT_MODIFIED: "Not Modified",
	NO_CONTENT: "No Content",
	OK: "OK",
	PARTIAL_CONTENT: "Partial Content",
	PAYLOAD_TOO_LARGE: "Payload Too Large",
	PAYMENT_REQUIRED: "Payment Required",
	PERMANENT_REDIRECT: "Permanent Redirect",
	PRECONDITION_FAILED: "Precondition Failed",
	PRECONDITION_REQUIRED: "Precondition Required",
	PROCESSING: "Processing",
	PROXY_AUTHENTICATION_REQUIRED: "Proxy Authentication Required",
	REQUESTED_RANGE_NOT_SATISFIABLE: "Requested Range Not Satisfiable",
	REQUEST_HEADER_FIELDS_TOO_LARGE: "Request Header Fields Too Large",
	REQUEST_TIMEOUT: "Request Timeout",
	REQUEST_URI_TOO_LONG: "Request-URI Too Long",
	RESET_CONTENT: "Reset Content",
	SEE_OTHER: "See Other",
	SERVICE_UNAVAILABLE: "Service Unavailable",
	SWITCHING_PROTOCOLS: "Switching Protocols",
	TEMPORARY_REDIRECT: "Temporary Redirect",
	TOO_MANY_REQUESTS: "Too Many Requests",
	UNAUTHORIZED: "Unauthorized",
	UNAVAILABLE_FOR_LEGAL_REASONS: "Unavailable For Legal Reasons",
	UNPROCESSABLE_ENTITY: "Unprocessable Entity",
	UNSUPPORTED_MEDIA_TYPE: "Unsupported Media Type",
	UPGRADE_REQUIRED: "Upgrade Required",
	USE_PROXY: "Use Proxy",
	VARIANT_ALSO_NEGOTIATES: "Variant Also Negotiates",
});
